### ISSUE TITLE
logger

### ISSUE THREAD

**Issue by bbcec** [smdhz/Logger#1]
请问这个记录插件现在是否还能用？如果可以用可以放出来吗谢谢

**Comment by smdhz** [comment]
用是能用，但它需要数据库(MS SQL Server Express)
你确定你需要？

**Comment by bbcec** [comment]
@smdhz 就是说需要安装专业的数据库之后才能用？

**Comment by smdhz** [comment]
1.2版可以记录到文件（KCV目录\ShipLog.csv）
但我觉得还是蛋疼，你可以试试鬼佬版KCV的记录插件先

**Comment by bbcec** [comment]
@smdhz 我找到鬼佬的记录插件好像都是没更新了，旧版的放进KCV会导致KCV开不了
